### ISSUE TITLE
Migrate out of Hackmd

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/RFCs#16]
As discussed during a Farcaster meeting on IRC, when the RFCs are in a good shape we want to move out of Hackmd. It was useful to get started and always was a temporary solution.

 - [x] Fix all linked between RFCs
 - [x] Add ToC, sadly those must be generated manually because GitHub doesn't support ToC in `md` format
 - [x] Remove all badges linking to Hackmd pages
 - [ ] Merge into and set `master` as default again
 - [x] Remove all math notation not supported by GitHub

**Comment by zkao** [comment]
- [ ]  convert latex into github-friendly format

**Comment by Lederstrumpf** [comment]
With the move away from hackmd, it's no longer necessary to be on GitHub for syncing. GitLab has LaTeX support, as well as the group `farcaster` available (not just `farcaster-project`). It makes more sense to use GitLab as the reference and mirror to GitHub. I can take care of the migration & mirroring process.

**Comment by h4sh3d** [comment]
I disagree with this, we communicated all about GitHub (I also have a personal preference for GitHub), and the mirror will not support LaTeX anyway, I don't see the point of moving everything now. LaTeX support is really not that important for these RFCs (at least it shouldn't).

**Comment by Lederstrumpf** [comment]
- We've just communicated GitHub in two community updates, and it's still accessible via that link
- The migration is trivial, I'll do it end-to-end
- The group name is much better
- LaTeX support improves readability _a lot_, in particular for adding formal specifications like petri nets, which we do want

**Comment by h4sh3d** [comment]
We already have setup the projects in GitHub, they link the PRs and Issues. I really don't see the point of changing that.

**Comment by h4sh3d** [comment]
The merge into master should be done after this got merged.

**Comment by Lederstrumpf** [comment]
> We already have setup the projects in GitHub, they link the PRs and Issues. I really don't see the point of changing that.

GitLab imports all of these in the migration process. If you change your mind in the future, or another reason to migrate emerges, I've registered https://gitlab.com/farcaster to prevent a name squatter.
