### ISSUE TITLE
tasks&events: `transaction_seen` -> `transaction_confirmations`

### ISSUE THREAD

**Issue by zkao** [farcaster-project/RFCs#40]
`transaction_seen` is emitted when it crosses some safety threshold, and is deemed irreversible/final

**Comment by h4sh3d** [comment]
To be able to update the client and follow the progression of a transaction we discussed previously about sending a `transaction_seen` each time the `confirmation` change, for:
- NaN: not seen at all
- 0: seen in the mempool
- 1: mined in 1 block
- 2: etc.

Maybe we want `transaction_seen` and `transaction_final` together.

**Comment by zkao** [comment]
`transaction_confirmations` seems like a more accurate name

**Comment by h4sh3d** [comment]
Fixed in #49
