### ISSUE TITLE
User Stories Clarification

### ISSUE THREAD

**Issue by synxero354** [farcaster-project/RFCs#50]
There are parts of the user stories that needs to be clarified in order to build much easily digestible content and user experience for non-tech individuals and non-developers.

**Maker Creating An Offer:**
1. What offer components must be manually defined? (what are the required inputs)?
2. What are the options to making an offer? Buy and Sell?
3. Can the offer be cancelled?

**Taker Taking Offer:**
1. Will there be a confirmation/validation for the Maker to ensure correct party is connected?

**Fee:**
1. What is the fee for?
2. What are the units to the fee?
3. Is there a limit to the fee?
4. Do they need to be manually defined?

**Time Parameters:**
1. What do the 2 time parameters do/mean for the users?

**Swap Phase:**
1. Are the wallet addresses submitted before or during the swapping phase?
2. Are there any mechanisms that prevent either user parties to cancel during the swap?

Overall, the document feels more like technical specifications, not necessarily user stories. User stories are more generic and provide a high-level overview of the functionalities based on specific user roles.

Ie. As a < type of user >, I want < some goal > so that < some reason >.

Please let me know whether the "Issues" or "Discussion" section is better for this post. Thanks!

**Comment by h4sh3d** [comment]
Thanks for the feedback, I'm starting working on that now

**Comment by synxero354** [comment]
Thanks for all the hard work @h4sh3d !

Is there any more clarification as to the punish functionality? What will be displayed to the user using? Will there be any sort of warning message in laymen terms to the user as to what the punishment will be in the case of a failed /time passed transaction?

Thanks!

**Comment by h4sh3d** [comment]
For sure the client must inform the user about when the punish might occur. But this will not be discussed in the RFCs for now as it can be done in many ways.

**Comment by synxero354** [comment]
I see, so it is right to presume that the punishment is also dependent on the client? It is not dictated by the user?

**Comment by h4sh3d** [comment]
No, not really.

The punishment happens only when the participant "Bob" (who's selling e.g. bitcoin for monero) fail to complete the refund, which is a "failure" from his daemon/client perspective.

The client prepare everything needed to refund and send it to the daemon way before it's needed, and the daemon monitor the blockchain to see if/when it should publish it.

A client should display some warnings to the user only if the refund procedure is happening but not yet completed.

But the user does not choose to punish, it'll be automatically done by the daemon who as the power to punish ("Alice"), when she waited enough time (i.e. the second timeout defined in the protocol).

**Comment by synxero354** [comment]
Right, so if I am understanding correctly Alice is the participant who made the offer, she dictates how long she's willing to wait for the refund.

The daemon (which is more or less universal), automatically dishes out the punishment as soon as the specified time has passed?

**Comment by h4sh3d** [comment]
> Right, so if I am understanding correctly Alice is the participant who made the offer, she dictates how long she's willing to wait for the refund from participant Bob.

Both can create an offer, Alice and Bob are related to what asset you want to exchange: Alice XMR->BTC and Bob BTC->XMR, this is forced by the protocol design and because Bitcoin and Monero blockchains are different. That's why we talk about Maker and Taker, to distinguish who makes and who takes, and in the offer we specify if the Maker will be Alice or Bob during the swap.

> The daemon (which is more or less universal because its the system) will automatically dishes out the punishment as soon as the specified time has passed?

Yes
